### ISSUE TITLE
Teaser trailer

### ISSUE THREAD

**Issue by samdebatin** [VroombaSociety/Monster-trons#1]
No teaser yet... Or any concept of what the game does. Anyone care to explain?

**Comment by piepie62** [comment]
As far as I can tell, it seems to be a lot like Pokémon, just under a different name and with minigames. Not completely sure yet, but I made the first day rough draft based on those two assumptions.

**Comment by Averyoda** [comment]
Monster-trons is kind of like a spoof of Pokemon, it's a comedic game with lots of inside jokes and generally funny moments.  For example:  there is a spoof of NAZI Germany called the Federalist United Communist Kingdom (F.U.C.K).  I'm adding the second person shooter that @samdebatin and I were joking about.
There are other jokes and puns in it as well.  I'm going to try to plan a meeting where the members who are working on this project can learn more about it and input their ideas as well as come up with a general story-line.
Sorry for the confusion.
I really just have a lot of ideas that are good, but I haven't got them all put together into a complete story.

**Comment by samdebatin** [comment]
That's good to know. I kind of get it now. Are you coming to practice tonight? I can talk about it a bit then.

**Comment by Averyoda** [comment]
Sorry, I can't until I get my stitches out on Tuesday.
Also, let's try to keep this to the game.
We can use the Core Hangout or the chatroom for personal things.

**Comment by samdebatin** [comment]
Sorry. We should come up with a good plot though. Please add any major plot points to the plotline.txt file.
