### ISSUE TITLE
Plotline

### ISSUE THREAD

**Issue by Averyoda** [VroombaSociety/Monster-trons#2]
I think that we should move the plot-line to google docs (despite my hatred for docs).  This is for four reasons: 1) It makes it more of a secret so people don't see the entire plot before playing the game 2) It's easier to update 3) It gives me more control of permissions (everyone who is in the admin team will have editing privileges) 4) It's a word processor, so it looks better stylistically.

**Comment by piepie62** [comment]
Good idea, I'm going to do that pretty soon.

**Comment by Averyoda** [comment]
Alright, I'm going to add more people to the docs.
